[package]
name = "fractal-hash-traversal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
digest = { version = "0.10.1", features = ["core-api"] }
sha2 = "0.10"
hex = "0.4.3"
